networks:
  app-api-network:
    name: app-api-network
    driver: bridge


services:
  app_psql:
    container_name: ${APP_PROJECT_PREFIX}-psql
    hostname: ${POSTGRES_HOST}
    restart: always
    build:
      context: ..
      dockerfile: ./docker/containers/pgsql/Dockerfile
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    env_file:
      - .env
    networks:
      - app-api-network
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=${POSTGRES_PORT}"]

  app_api:
    container_name: ${APP_PROJECT_PREFIX}-api
    build:
      context: ..
      dockerfile: ./docker/containers/api/Dockerfile
    restart: always
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    networks:
      - app-api-network

    depends_on:
      - app_psql
    volumes:
      - ../app:/app
    env_file:
      - .env
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port ${APP_HTTP_PORT} --reload"
